GET http://localhost:3000/subscribers

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Person 2",
    "subscribedToChannel": "Example 2"

}

###

GET http://localhost:3000/subscribers/6275a5d25a33a463aff43288

###

DELETE http://localhost:3000/subscribers/6275a5d25a33a463aff43288